version: "3.1"

services:
  nginx:
    image: nginx
    depends_on:
      - apionibus
      - phpmyadmin
    volumes:
      - ./conf/default.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/ssl/:/etc/nginx/ssl/
      - ./volumes/nginx/conf.d/:/etc/nginx/conf.d/
      - ./volumes/nginx/www/:/var/www/
      - ./letsencrypt/www:/var/www/letsencrypt
      - ./letsencrypt/etc:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    links:
      - apionibus
      - phpmyadmin
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 12000:80
    links:
      - db
  apionibus:
    image: golang:1.9
    ports:
      - 5000:5000
    depends_on:
      - db
    working_dir: /go/src/github.com/rodrigo-brito/bus-api-go
    volumes:
      - ../:/go/src/github.com/rodrigo-brito/bus-api-go
    command: go run main.go
    restart: always